schema: workflow/2022.04
name: try
settings:
  error_notification: true
triggers:
- id: hi_6LHYV5L
steps:
- namespace: code
  runtime: nodejs18.x
  uses: "./code/entry.js"
  props:
    _csrfToken: "{{steps.trigger.event.body._csrfToken}}"
    animal_ids: "{{steps.trigger.event.body.internal_id}}"
    apiKey: '{{steps.trigger.event.body["X-Api-Key"]}}'
    cookie: "}{{steps.trigger.event.body.Cookie}}"
- namespace: code_1
  disabled: true
  runtime: golang
  uses: "./code_1/entry.go"
- namespace: return_http_response
  runtime: nodejs18.x
  uses: http-return-http-response@0.0.3
  props:
    resStatusCode: 200
    resHeaders: {}
    resBody: "{{steps.code.$return_value.kennelCardUrl.kennelCardsUrl}}\n"

